kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: sso-proxy
spec:
  lookupPolicy:
    local: false
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: sample-app
spec:
  lookupPolicy:
    local: false