kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "helm.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "helm.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
