kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: sample-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'sample-app:latest'
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:11'
  source:
    type: Git
    git:
      uri: 'https://github.com/cloudfirst-dev/kerberos-sidecar'
    contextDir: /sample-app
  runPolicy: Serial