apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sso-builder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-builds
rules:
  - apiGroups:
      - 'build.openshift.io'
    resources:
      - "buildconfigs/instantiate"
    verbs:
      - create
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: builder-create-builds
subjects:
  - kind: ServiceAccount
    name: sso-builder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-builds